services:
  conty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conty
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
